# Generated by Django 5.1.7 on 2025-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teacher_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
