# Generated by Django 5.1.7 on 2025-04-03 09:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_unique_id',
        ),
        migrations.RenameField(
            model_name='question_answer',
            old_name='qa_id',
            new_name='question_ans_unique_id',
        ),
        migrations.RenameField(
            model_name='question_answer_message',
            old_name='qa_id',
            new_name='question_ans_massage_unique_id',
        ),
        migrations.RenameField(
            model_name='question_answer_message',
            old_name='qam_id',
            new_name='question_ans_mess_unique_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='variant_id',
            new_name='variant_unique_id',
        ),
        migrations.RenameField(
            model_name='variantitem',
            old_name='variant_item_id',
            new_name='variant_item_unique_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_unique_id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=12, unique=True),
        ),
    ]
