# Generated by Django 5.1.7 on 2025-04-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_course_id_course_course_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_unique_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='question_answer',
            old_name='question_ans_unique_id',
            new_name='qa_id',
        ),
        migrations.RenameField(
            model_name='question_answer_message',
            old_name='question_ans_massage_unique_id',
            new_name='qa_id',
        ),
        migrations.RenameField(
            model_name='question_answer_message',
            old_name='question_ans_mess_unique_id',
            new_name='qam_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='variant_unique_id',
            new_name='variant_id',
        ),
        migrations.RenameField(
            model_name='variantitem',
            old_name='variant_item_unique_id',
            new_name='variant_item_id',
        ),
    ]
