# Generated by Django 5.1.7 on 2025-04-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_course_unique_id_course_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_unique_id',
            new_name='teacher_id',
        ),
    ]
