# Generated by Django 5.1.7 on 2025-04-04 03:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_teacher_unique_id_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=12),
        ),
    ]
