# Generated by Django 5.1.7 on 2025-04-04 04:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=12),
        ),
    ]
