# Generated by Django 5.1.7 on 2025-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_review_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
