# Generated by Django 5.1.7 on 2025-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_variantitem_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='module',
            field=models.IntegerField(),
        ),
    ]
