# Generated by Django 5.1.7 on 2025-04-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_variantitem_module_variant_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, default='/backend/static/image/teacher.jpg', null=True, upload_to='course_file'),
        ),
    ]
