# Generated by Django 5.1.7 on 2025-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, default='/course_file/teacher.jpg', null=True, upload_to='course_file'),
        ),
    ]
