"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import userauths
import environ
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-44rlwe@=rq_q8yb^p4e7!55(qd^o((1-lo&t^w6^i5#nxlx#=_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #! USING CUSTOM UI FOR ADMIN
    'jazzmin',
    
    #! DEFAULT APP CONFIGURATION
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #! CUSTOM APP CONFIGURATION
    'core',
    'api',
    'userauths',
    
    #! third party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'anymail',
    'drf_yasg'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

AUTH_USER_MODEL = 'userauths.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




#! MAKING  CUSTOM JAZZMIN_SETTINGS

JAZZMIN_SETTINGS = {
    # Title of the window (Admin panel title)
    "site_title": "Learning System Admin",

    # Title on the login screen (Shorter version of site title)
    "site_header": "Learning Platform",

    # Title on the brand (appears on the top left)
    "site_brand": "Learning Hub",

    # Logo to use for the site (Path to logo image in static files)
    # "site_logo": "courses/img/logo.png",

    # Logo for login form (dark theme)
    # "login_logo_dark": "courses/img/login_logo_dark.png",

    # CSS classes for the logo (Used for styling)
    "site_logo_classes": "img-circle",

    # Site favicon (appears in browser tab)
    # "site_icon": "courses/img/favicon.ico",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Learning Hub Admin Panel",

    # Copyright on footer
    "copyright": "Learning Hub Pvt. Ltd.",

    # Model admins to be included in search bar
    "search_model": ["auth.User", "auth.Group", "courses.Course", "courses.Lesson"],

    # User avatar field (Can be used for user profile images)
    "user_avatar": "users.Profile.avatar",

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/learninghub", "new_window": True},
        {"app": "courses"},
        {"model": "courses.Course"},
    ],

    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "Profile", "url": "admin:auth_user_change", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/learninghub", "new_window": True},
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    # "hide_apps": ["auth", "contenttypes"],
    # "hide_models": [],
    "order_with_respect_to": ["courses", "courses.Course", "courses.Lesson"],

    # Custom links to add
    "custom_links": {
        "courses": [{
            "name": "Create Course",
            "url": "admin:courses_course_add",
            "icon": "fas fa-plus-circle",
            "permissions": ["courses.add_course"]
        }]
    },

    # Custom icons for models in side menu
    "icons": {
        "courses": "fas fa-chalkboard-teacher",
        "courses.Course": "fas fa-book-open",
        "courses.Lesson": "fas fa-bookmark",
    },

    #################
    # Related Modal #
    #################
    "related_modal_active": True,  # Use modals for related fields

    #############
    # UI Tweaks #
    #############
    # "custom_css": "courses/css/custom_admin.css",  # Custom admin CSS for styling
    # "custom_js": "courses/js/custom_admin.js",  # Custom admin JavaScript for additional features
    "use_google_fonts_cdn": True,  # Use Google Fonts for a modern UI
    "show_ui_builder": False,  # Disable the UI customizer (optional)

    ###############
    # Change view #
    ###############
    "changeform_format": "collapsible",  # Use collapsible view for forms
    "changeform_format_overrides": {
        "courses.Course": "horizontal_tabs",  # Tabs for course model form
        "courses.Lesson": "vertical_tabs",   # Tabs for lesson model form
    },

    # Add a language dropdown in the admin panel
    # "language_chooser": True,
}




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'noreplay@gmail'


FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")