# Generated by Django 5.1.7 on 2025-03-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
