# Generated by Django 5.1.7 on 2025-04-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_profile_about_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_unique_id',
            new_name='user_id',
        ),
    ]
